/*
 * generated by Xtext 2.11.0
 */
package de.unimuenster.pi.ide

import com.google.inject.Guice
import de.unimuenster.pi.BinDslRuntimeModule
import de.unimuenster.pi.BinDslStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class BinDslIdeSetup extends BinDslStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new BinDslRuntimeModule, new BinDslIdeModule))
	}
	
}
